/* auto-generated by NAPI-RS */
/* eslint-disable */

export interface PackageInfo {
  name: string;
  versionRange: string;
  depType: string;
}

export interface CheckOptions {
  registry?: string;
  target?: string;
  concurrency?: number;
  timeoutMs?: number;
  cacheFile?: string;
  cacheTtlSeconds?: number;
  includePrerelease?: boolean;
  retries?: number;
}

export interface UpdateResult {
  name: string;
  current: string;
  currentVersion: string;
  latest: string;
  newRange: string;
  updateType: string;
  depType: string;
}

export interface CheckResult {
  updates: UpdateResult[];
  cacheHits: number;
  cacheMisses: number;
  fetchTimeMs: number;
  totalTimeMs: number;
}

export declare function checkUpdates(
  packages: PackageInfo[],
  options: CheckOptions,
): Promise<CheckResult>;

export declare function clearCache(cacheFile?: string): void;
